#!/usr/bin/env python3
"""
build_editor.py - Bundle the modular EntropyEditor into a single self-contained file.

Three outputs:
  1. editor/js/viewer-template.js  - a generated, self-contained copy of the full
     EntropyExplainer reader (the real Viewer: themes, sidebar nav, read-all/focus,
     search, progress, proper markdown), with a data placeholder. The editor's
     "View" button injects the current content into this template and opens it in a
     new tab, so previewing uses the actual reader.
  2. editor.html  - the whole editor (HTML + CSS + JS, including the viewer template)
     inlined into one double-clickable file.
  3. explainer/js/viewer-template.js  - an identical copy of output #1, loaded by the
     explainer so its "Save as standalone HTML" button injects the current book into
     the very same generated reader (instead of a hand-maintained duplicate viewer).

The modular source under editor/ (and explainer/) stays the place to make changes;
re-run this script to refresh both outputs.

Usage:  py build_editor.py            # write both outputs
        py build_editor.py --check    # verify outputs are in sync; exit 1 if stale (no writes)
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "editor"
EX = ROOT / "explainer"
OUT = ROOT / "editor.html"

# Editor bundle: CSS cascade order, then JS dependency/init order.
# viewer-template.js (generated below) must load before palette.js, which uses it.
CSS_FILES = ["css/base.css", "css/panels.css", "css/editor.css"]
JS_FILES = ["js/state.js", "js/tree.js", "js/editor.js",
            "js/viewer-template.js", "js/palette.js", "js/graph.js", "js/app.js"]

# Explainer (the real reader) — same load order as explainer/index.html.
EX_CSS = ["css/base.css", "css/themes.css", "css/components.css",
          "css/accessibility.css", "css/responsive.css"]
EX_JS = ["js/markdown.js", "js/state.js", "js/navigation.js", "js/renderer.js",
         "js/themes.js", "js/accessibility.js", "js/media.js", "js/graph.js",
         "js/standalone.js", "js/reading-mode.js", "js/app.js"]

DATA_TOKEN = "__ENTROPY_PREVIEW_DATA__"


def read(base, rel):
    p = base / rel
    if not p.exists():
        print(f"Error: missing source file {p}")
        sys.exit(1)
    return p.read_text(encoding="utf-8")


def build_viewer_template():
    """Self-contained explainer reader with a data placeholder + auto-load bootstrap."""
    html = read(EX, "index.html")

    css = "\n".join(f"/* ===== explainer/{c} ===== */\n{read(EX, c)}" for c in EX_CSS)
    if "</style>" in css:
        print("Error: explainer CSS contains a literal </style>; cannot inline.")
        sys.exit(1)

    # </script> inside JS only ever appears in string literals -> escape so it can't
    # close the reader's <script> tag once this template is materialised in a blob.
    js = "\n".join(f"// ===== explainer/{j} =====\n{read(EX, j)}" for j in EX_JS)
    js = js.replace("</script>", "<\\/script>")

    # If localStorage is blocked (opaque/blob origin), install an in-memory shim so
    # the reader still runs. Must precede the explainer JS (state.js reads at init).
    shim = (
        "try{localStorage.getItem('__entropy_probe');}catch(e){try{var __ls={};"
        "Object.defineProperty(window,'localStorage',{configurable:true,value:{"
        "getItem:function(k){return Object.prototype.hasOwnProperty.call(__ls,k)?__ls[k]:null},"
        "setItem:function(k,v){__ls[k]=String(v)},removeItem:function(k){delete __ls[k]},"
        "clear:function(){__ls={}},key:function(i){return Object.keys(__ls)[i]||null},"
        "get length(){return Object.keys(__ls).length}}});}catch(e2){}}"
    )
    boot = (
        f"window.__ENTROPY_PREVIEW__={DATA_TOKEN};"
        "document.addEventListener('DOMContentLoaded',function(){"
        "try{if(window.__ENTROPY_PREVIEW__)State.loadContent(window.__ENTROPY_PREVIEW__);}"
        "catch(err){console.error('preview load failed',err);}});"
    )

    # Strip the modular link/script tags and inline everything.
    html = re.sub(r'[ \t]*<link rel="stylesheet" href="css/[^"]+">\n?', "", html)
    html = re.sub(r'[ \t]*<script src="js/[^"]+"></script>\n?', "", html)
    html = html.replace("<title>EntropyExplainer</title>", "<title>Viewer — EntropyExplainer</title>", 1)
    html = html.replace("</head>", f"    <style>\n{css}\n    </style>\n</head>", 1)
    inject = f"    <script>\n{shim}\n{js}\n</script>\n    <script>\n{boot}\n</script>\n"
    html = html.replace("</body>", inject + "</body>", 1)
    return html


def render_viewer_template_js(template):
    """Full text of the generated js/viewer-template.js (no disk write)."""
    return (
        "// GENERATED by build_editor.py — do not edit by hand.\n"
        "// Self-contained EntropyExplainer reader used by the editor's View button.\n"
        "// Regenerate with: py build_editor.py\n"
        "const VIEWER_TEMPLATE = " + json.dumps(template) + ";\n"
    )


def render_editor_html(viewer_js):
    """Build the single-file editor.html string (no disk write).

    viewer_js is the freshly rendered js/viewer-template.js content; it is used in
    place of the on-disk copy so the bundle never inherits a stale generated file.
    """
    html = read(SRC, "index.html")

    css = "\n".join(f"/* ===== {rel} ===== */\n{read(SRC, rel)}" for rel in CSS_FILES)
    if "</style>" in css:
        print("Error: editor CSS contains a literal </style>; cannot inline.")
        sys.exit(1)

    # Escape </script> (only present inside viewer-template.js's string literal) so
    # it can't close the editor's own inlined <script> block.
    parts = []
    for rel in JS_FILES:
        body = viewer_js if rel == "js/viewer-template.js" else read(SRC, rel)
        body = body.replace(chr(60) + '/script>', chr(60) + chr(92) + '/script>')
        parts.append(f"// ===== {rel} =====\n{body}")
    js = "\n".join(parts)

    html = re.sub(r'[ \t]*<link rel="stylesheet" href="css/[^"]+">\n?', "", html)
    html = re.sub(r'[ \t]*<script src="js/[^"]+"></script>\n?', "", html)
    if "</head>" not in html or "</body>" not in html:
        print("Error: editor index.html missing </head> or </body>.")
        sys.exit(1)
    html = html.replace("</head>", f"    <style>\n{css}\n    </style>\n</head>", 1)
    html = html.replace("</body>", f"    <script>\n{js}\n    </script>\n</body>", 1)
    html = html.replace(
        "<title>EntropyEditor</title>",
        "<title>EntropyEditor</title>\n    <!-- Single-file build from build_editor.py. Edit the modular source under editor/ then rerun. -->",
        1,
    )
    return html


def current_text(path):
    """On-disk text of an output file, or None if it does not exist yet."""
    return path.read_text(encoding="utf-8") if path.exists() else None


def main(check=False):
    template = build_viewer_template()
    viewer_js = render_viewer_template_js(template)
    html = render_editor_html(viewer_js)
    viewer_path = SRC / "js/viewer-template.js"
    ex_viewer_path = EX / "js/viewer-template.js"

    if check:
        stale = []
        if current_text(viewer_path) != viewer_js:
            stale.append("editor/js/viewer-template.js")
        if current_text(ex_viewer_path) != viewer_js:
            stale.append("explainer/js/viewer-template.js")
        if current_text(OUT) != html:
            stale.append("editor.html")
        if stale:
            print("OUT OF DATE - outputs differ from source. Rerun `py build_editor.py`:")
            for f in stale:
                print(f"  - {f}")
            sys.exit(1)
        print("In sync: editor + explainer viewer-template.js and editor.html match the source.")
        return

    viewer_path.write_text(viewer_js, encoding="utf-8", newline="\n")
    print(f"Generated editor/js/viewer-template.js  ({len(template):,} bytes of embedded viewer)")

    ex_viewer_path.write_text(viewer_js, encoding="utf-8", newline="\n")
    print(f"Generated explainer/js/viewer-template.js  (shared reader template for Save-as-HTML)")

    OUT.write_text(html, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT}")
    print(f"  {len(html):,} bytes  |  {len(CSS_FILES)} CSS + {len(JS_FILES)} JS inlined (incl. embedded viewer)")


if __name__ == "__main__":
    argv = sys.argv[1:]
    unknown = [a for a in argv if a != "--check"]
    if unknown:
        print(f"Unknown argument(s): {' '.join(unknown)}")
        print("Usage: py build_editor.py [--check]")
        sys.exit(2)
    main(check="--check" in argv)
