/* ============================================
   STANDALONE — Export a self-contained HTML copy
   of the reader with the current book embedded.

   This reuses VIEWER_TEMPLATE — the self-contained
   reader generated by build_editor.py from the real
   explainer source (same template the editor's
   "Open in Viewer" uses). Injecting the book JSON
   into its data placeholder yields an export that
   IS the real reader (read-all, graph, media, themes,
   a11y, footnotes) and never drifts out of sync.

   Regenerate the template with: py build_editor.py
   ============================================ */

const Standalone = (() => {

    function exportToHtml(data, toastFn) {
        if (!data) {
            if (toastFn) toastFn('Load a file first');
            return;
        }
        // VIEWER_TEMPLATE is a global from js/viewer-template.js (generated). It is
        // absent inside an already-exported file or the editor preview — degrade
        // gracefully rather than emit a broken export.
        if (typeof VIEWER_TEMPLATE === 'undefined') {
            if (toastFn) toastFn('Viewer template missing — run: py build_editor.py');
            return;
        }

        // Embed the book JSON in the template's data placeholder. Neutralize "</"
        // so the JSON can't terminate the <script> it lands in; pass the value as a
        // function so "$" sequences in the data aren't read as regex backreferences.
        // The placeholder is assembled in two halves on purpose: this file is itself
        // inlined into the template by build_editor.py, and a literal contiguous
        // token here would become a SECOND placeholder that steals the replacement.
        const placeholder = '__ENTROPY_PREVIEW' + '_DATA__';
        const jsonStr = JSON.stringify(data).replace(/<\//g, '<\\/');
        const html = VIEWER_TEMPLATE.replace(placeholder, () => jsonStr);

        const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        const title = (data.meta && data.meta.title) || 'viewer';
        a.download = title.replace(/[^a-zA-Z0-9 _-]/g, '').trim() || 'viewer';
        a.download += '.html';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        if (toastFn) toastFn('Standalone file downloaded');
    }

    return { exportToHtml };
})();
